### ISSUE TITLE
scrollbar-hidden doesnt work with containers

### ISSUE THREAD

**Issue by montijr2007** [bfwg/ngx-drag-scroll#105]
I was having an issue using a complex element inside of my dragScroll, namely a Material Design Card. I was unable to get the scrollbar-hidden to work for the horizontal scroll bar and had to forcefully remove it by wrapping my dragScroll in a container with overflow-x hidden, like so:
`<div overflow-x: hidden !important;> <div dragScroll scrollbar-hidden="true" [more stuff here]></div></div>` 

This worked for the web browser, however, the drag-scroll would not work on mobile devices. I figured there was an issue with the dragScroll not working with containers such as "div".

After copying/pasting code from the demo app, I found that the height property of the dragScroll element needed to be specified. This fixed my issue. Please close this as a non-issue

**Comment by bfwg** [comment]
Closing as this is no longer an issue.
