### ISSUE TITLE
mouseMoveListener affecting entire document

### ISSUE THREAD

**Issue by MNorgren** [bfwg/ngx-drag-scroll#106]
After some investigation, I have found that the mouseMoveListener is preventing "text selection" on any part of the document. 

I've modified the directive slightly to enable the text-selection outside of the native element changing the onMouseMove return statement to:
`return !this.isPressed; //Only return false if the element was pressed, otherwise return true`

See the full function:

      onMouseMove(e: MouseEvent) {
            if (this.isPressed && !this.disabled) {
            e.preventDefault();
            // Drag X
            if (!this.xDisabled && !this.dragDisabled) {
              this.el.nativeElement.scrollLeft =
              this.el.nativeElement.scrollLeft - e.clientX + this.downX;
              this.downX = e.clientX;
            }
            // Drag X
            if (!this.xDisabled && !this.dragDisabled) {
              this.el.nativeElement.scrollLeft =
              this.el.nativeElement.scrollLeft - e.clientX + this.downX;
              this.downX = e.clientX;
            }
            // Drag Y
            if (!this.yDisabled && !this.dragDisabled) {
              this.el.nativeElement.scrollTop =
              this.el.nativeElement.scrollTop - e.clientY + this.downY;
              this.downY = e.clientY;
            }
          }
          return !this.isPressed; //Only return false if the element was pressed, otherwise return true
      }

**Comment by bfwg** [comment]
Should be fixed in 1.7.2.
