### ISSUE TITLE
Metadata version mismatch for module 

### ISSUE THREAD

**Issue by NikhilRadadiya** [bfwg/ngx-drag-scroll#108]
```
ERROR in Error: Metadata version mismatch for module project-path/node_modules/ngx-drag-scroll/index.d.ts, found version 4, expected 3, resolving symbol ProjectsModule in project-path/projects/projects.module.ts, resolving symbol ProjectsModule in project-path/src/app/components/projects/projects.module.ts
```

I have beent trying to use `ngx-drag-scroll` but getting above error.

**Comment by Satish-Lakhani** [comment]
Facing the same issue with angular 4.4.6

`ERROR in Error: Metadata version mismatch for module /node_modules/ngx-drag-scroll/index.d.ts, found version 4, expected 3, resolving symbol AppModule in app.module.ts, resolving symbol AppModule in app/app.module.ts`

**Comment by bfwg** [comment]
This is due to Angular version mismatch. Update Angular version to `5.x.x` should resolve the issue.

**Comment by bfwg** [comment]
Closing this for now, let me know if you have more question and I can re-open this.
