### ISSUE TITLE
Positioning after moveLeft()/moveRight()

### ISSUE THREAD

**Issue by wojofe** [bfwg/ngx-drag-scroll#109]
Hey again!

When invoking moveLeft() or moveRight() after dragging a bit with snap-disabled="true" the jump goes to the wrong position, seemingly the position before dragging.

Kind regards!

**Comment by bfwg** [comment]
Hey @wojofe 
Thanks for reporting this. I've made a PR and investigating into this.

**Comment by wojofe** [comment]
Behavior has changed now, but I see a new bug: Invoking moveRight() does not move the slider sometimes (moveLeft() always works). On my machine, with the example I am running right now, I get a repeatable pattern of 1,0,1,1,0,1 (1 slider moves one position to the right, 0 sliders does not move), i.e. 2 out of 6 clicks on my "right" button do nothing.

**Comment by bfwg** [comment]
Hi @wojofe , I can't seem to reproduce the issue with the demo app. Can you replace https://github.com/bfwg/ngx-drag-scroll/blob/develop/demo/app/home/home.component.html#L4-L11 with the below code, and test again? 

```html
    <div class="demo-one"
      dragScroll
      drag-scroll-y-disabled="true"
      snap-disabled="true"
      scrollbar-hidden="true"
      (reachesLeftBound)="leftBoundStat($event)"
      (reachesRightBound)="rightBoundStat($event)"
      #nav
      >

```

Thanks!

**Comment by wojofe** [comment]
I fear I do not understand what you want me to do.

In the meantime I noticed another thing: When I click left (i.e. invoke this.ds.moveLeft();) multiple times without waiting for the movement to end, the bar jumps to weird places also.

Also, if I do not encapsulate like this
```
  reachesLeft(event: any) {
    setTimeout(() => {
      this.toggleLeftNav = event;
    }, 0);
  }
```
I get
`ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.`

**Comment by bfwg** [comment]
Hey, @wojofe . Could you fork this project and run the demo app with your breaking change? It is under the demo folder. This way, I can take a closer look of what is going wrong.

**Comment by bfwg** [comment]
Closing due to no response
