### ISSUE TITLE
angular 5 and universal support

### ISSUE THREAD

**Issue by hesampour** [bfwg/ngx-drag-scroll#111]
Dose this module work in angular 5? I tried a lot but i cant get this package work for my angular 5 project?
and if I get the module work can i use it with angular universal?

**Comment by akkumar** [comment]
@hesampour  - if it is not working with ng5 - can you share error log  as applicable ? 

Issue #68 talks about ng universal but it is not in yet.

**Comment by bfwg** [comment]
Closing due to no response.
