### ISSUE TITLE
Some other components/listeners no longer receive certain mouse events when dragscroll is present

### ISSUE THREAD

**Issue by wojofe** [bfwg/ngx-drag-scroll#113]
Title says it all.

Debugging revealed these listeners to be at fault:
```
345    this.mouseMoveListener = renderer.listen('document', 'mousemove', this.onMouseMoveHandler);
346    this.mouseUpListener = renderer.listen('document', 'mouseup', this.onMouseUpHandler);
```

The events are not handed down to other components as they are prevented at the document level.

**Comment by bfwg** [comment]
Hi @wojofe , I'm trying to reproduce by adding a `mousemove` event listener in the https://github.com/bfwg/ngx-drag-scroll/blob/develop/demo/app/home/home.component.ts#L37 , but I can't seem to reproduce it. 

Can you give me a code snipped using the demo app?

Thanks.

**Comment by wojofe** [comment]
Just place a https://material.angular.io/components/menu/overview dropdown on the same page with dragscroll and then try to select something from it.

**Comment by wojofe** [comment]
I have gone into it a bit deeper and it turns out it was another component/module that I tied to the material component that was affected. After swapping that one out for a simpler solution to problem no longer occurs, so unless other people also come up with problems regarding mouseevents not reaching their destination in the presence of dragscroll I would say this does no longer qualify as a bug.

Unfortunately I am not knowledgeable enough on the component that I removed in order to explain what the specific mechanism which got disturbed by the event handling was.
