### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by akkumar** [bfwg/ngx-drag-scroll#114]
The releases page - https://github.com/bfwg/ngx-drag-scroll/releases does not contain the recent releases. (not the 1.6.x or the 1.7.x ). 

@bfwg  - Just curious what the release process looks like. 

Suggested one is here - https://help.github.com/articles/creating-releases/ .  

Assuming the commits are merged from develop to master and the release is made from master, the releases for the project should contain the more recent releases as well. 

Also assuming the releases are properly tagged by that process already - 

```console
git log --pretty=oneline master..<previous release tag>
```
should list the changelog automatically for us to maintain the changelog better.

**Comment by bfwg** [comment]
The commits are merged from develop to master and then an npm publish is released from master. I have been ignoring GitHub releases, and you are right, we should come up with a GitHub release flow. 
I suggest we start tagging them. Every npm version should have a git tag, and maybe whenever there is a major release version, we include the changes from the CHANGELOG.md?

**Comment by bfwg** [comment]
I've just pushed the tag for 1.7.3

**Comment by akkumar** [comment]
I agree we should start tagging every release. 

I was under the impression that the github release process would automatically tag the release as well. 

If that were the case - we can easily create changelog to every major / minor release just by using the git log command. 

```console
git log --pretty=oneline master..<previous release tag>
```

So -the changelog would become redundant that way.

**Comment by akkumar** [comment]
I am looking at the changelog for angular-cli project ( say, for example ). 
https://github.com/angular/angular-cli/releases . 

Seems sort of concise and seems auto-generated / pasted when a release is being made. 

We can always expand the information based on the commits we have as you had illustrated above. 

But if appropriate tagging has been done - we can possibly create the changelog dynamically based on tag difference. (including the detailed log as you had given above for example) . 

Also curious if the 1.7.3 tag had been created manually by you or created automatically ?

**Comment by bfwg** [comment]
The 1.7.3 tag is created manually, and if I click create a release, the content is empty which means we still have to draft them ourselves.

**Comment by akkumar** [comment]
Thanks @bfwg for the clarification. 

This is not an 'issue' with the product per se. So closing it for now.

**Comment by akkumar** [comment]
#118 - conventional-changelog could be used to generate the changelog dynamically. More details in #118 .
