### ISSUE TITLE
very slow and choppy drag in IE 11

### ISSUE THREAD

**Issue by wojofe** [bfwg/ngx-drag-scroll#119]
When using IE 11 dragging is very slow and choppy - and also causes some text to get selected (dragging creates a bit of an offset between the cursor position and the clicked on position in the dragscroll - and that offset ends up being selected (best seen with text)).

**Comment by bfwg** [comment]
@wojofe have you tried with 1.7.6

**Comment by bfwg** [comment]
I'm closing this issue. Please let me know if you want to reopen.
