### ISSUE TITLE
drag-scroll inside a list

### ISSUE THREAD

**Issue by PraneethKP** [bfwg/ngx-drag-scroll#120]
Hi,
       I am using drag-scroll inside a list, so the #nav tag is repeating. Because of that repetition the next and previous options are not working,, Please suggest some alternate or the exact way of usage in my case.

**Comment by bfwg** [comment]
Hi @PraneethKP 
Sorry for the late reply, have you tried to put the carousel with the navigation buttons in a separate component? This should make #nav encapsulated.
