### ISSUE TITLE
Highlight text is not working in Chrome

### ISSUE THREAD

**Issue by Sipike** [bfwg/ngx-drag-scroll#121]
Hi,
I'm using this module, but I cannot highlight text where ngx-drag-scroll is active.
You can check this out on Demo page.

**Chrome version**: 63.0.3239.132
**OS**: macOS High Sierra 10.13.3

**Comment by bfwg** [comment]
Hi, have you tried with the latest version `1.7.3`? The issue should be resolved. The demo page is outdated and I will update it shortly.
