### ISSUE TITLE
rightNavDisabled false after reaching end of carousel 

### ISSUE THREAD

**Issue by jtcrowson** [bfwg/ngx-drag-scroll#122]
Steps to reproduce in demo app:
- Number of images in the `imagelist`: 5 images (done here: [Github Fork](https://github.com/jtcrowson/ngx-drag-scroll) & [Stackblitz](https://stackblitz.com/github/jtcrowson/ngx-drag-scroll)) 
- Browser window width: `1350px`
- Click the right button once to navigate the carousel to show the entire 5th image.

Bug:
- The 'right' button is still enabled despite there being to more cards to show.
  - `rightNavDisabled` should be `true` in this scenario, but is `false`.
- Can't navigate to the entire 5th image using scroll, must use the arrow.  Scroll snaps the carousel back to the first image.

<img width="1349" alt="screen shot 2018-03-06 at 11 19 08 am" src="https://user-images.githubusercontent.com/3779096/37044321-25b3444c-2131-11e8-9cd9-2a65c0c7eaec.png">

**Comment by jtcrowson** [comment]
After more research, this bug is fixed by removing `this.currIndex !== 0` in 

```
onScroll() {
  ...
  if ((ele.scrollLeft + ele.offsetWidth) >= ele.scrollWidth && this.currIndex !== 0) {
    this.scrollReachesRightEnd = true;
  } else {
    this.scrollReachesRightEnd = false;
  }
  ...
}
```
->

```
onScroll() {
  ...
  if ((ele.scrollLeft + ele.offsetWidth) >= ele.scrollWidth) {
    this.scrollReachesRightEnd = true;
  } else {
    this.scrollReachesRightEnd = false;
  }
  ...
}
```

The git blame says it was added by #46.

**Comment by bfwg** [comment]
Thanks for reporting this issue @jtcrowson ! I will look into it as soon as possible.

**Comment by bfwg** [comment]
Hi @jtcrowson , the issue should be fixed in 1.7.5. Thanks again for your effort. Please let me know if you want to reopen this issue.

**Comment by jtcrowson** [comment]
Awesome, thanks!  Any insight to why that code was originally added?

**Comment by bfwg** [comment]
Sadly I cannot recall the reason 😛
