### ISSUE TITLE
npm install ngx-drag-scroll@1.7.5 fails to install the module correctly

### ISSUE THREAD

**Issue by sadaktx** [bfwg/ngx-drag-scroll#124]
With the latest changes, npm install does not download the ngx-drag-scroll.d.ts or .js or .j.map files and this breaks the ng build - failing to find ngx-drag-scroll module in app.module.ts.

**Comment by bfwg** [comment]
@sadaktx Thanks for reporting, I'm looking into the issue.

**Comment by bfwg** [comment]
Please update to 1.7.6, thanks!

**Comment by sadaktx** [comment]
Thanks for the quick turn around to fix the issue!
