### ISSUE TITLE
Hide scrollbar failure when resize viewport from wide to narrow

### ISSUE THREAD

**Issue by burangwojin** [bfwg/ngx-drag-scroll#127]
#### What are the steps to reproduce?
1. _[scrollbar-hidden]="true"_
2. load page in a wide enough viewport
3. narrow viewport. when resizing narrow enough, scrollbar-x will display even if  _[scrollbar-hidden]="true"_

This is bug maybe, i think.

**Comment by bfwg** [comment]
Thanks for reporting this, I'll take a look when I'm free.

**Comment by bfwg** [comment]
Hi @burangwojin , I could not reproduce the error from the demo app. Can you use the [demo](https://bfwg.github.io/ngx-drag-scroll/) to test and possibly write down the reproduce steps?

**Comment by jufarhi** [comment]
Hi @bfwg,

You can't reproduce in the demo because the height is hardcoded in the css for the wrapper element.

Remove the height in the css and you will see the problem.

**Comment by burangwojin** [comment]
sorry for leaving behind this issue for long time.   

Actually,  hardcoded brings this problem as @jufarhi said after I have read _ngx-drag-scroll.ts_
It is not easy for me to reproduce on https://stackblitz.com.

I think you should do _**setScrollBar()**_ or _ **checkScrollbar()**_ **when _window:resize**_ so that the height of wrapper element will be recalculate

At last, I solve this problem in my own program by _**renderer.setStyle()**_ function

**Comment by bfwg** [comment]
@burangwojin do you mind to create a PR with your solution?

**Comment by bfwg** [comment]
@jufarhi the height of the wrapper has to be declared explicitly.

**Comment by burangwojin** [comment]
I will try my best, but without deadline.   
Actually, this ngx lib about drag&drop is good enough for me when I using.

**Comment by IlCallo** [comment]
I'm interested in this as well

**Comment by bfwg** [comment]
Is this still occurring in the 2.0.2?

**Comment by nadav-lin** [comment]
Still happens to me in, 2.0.2

**Comment by IlCallo** [comment]
Can't reproduce on 2.0.2, but I'm not sure if it's actually fixed or I just forgot how to replicate the issue 🤔
Without a stackblitz replicating the error in previous versions it's a bit hard to find out if it's actually solved or not
