### ISSUE TITLE
Do not reset scroll location on disabling/enabling the drag.

### ISSUE THREAD

**Issue by TimP4w** [bfwg/ngx-drag-scroll#133]
* **I'm submitting a ...**
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
When disabling/enabling drag, the page gets scrolled to the starting position.

* **What is the expected behavior?**
Leave the scroll at the current position without resetting it.

* **What is the motivation / use case for changing the behavior?**
In my case: a game map whit draggable elements inside. When moving one of those I disable the drag'n'scroll but the content gets moved and I can't drop the element.

* **Please tell us about your environment:**
No need.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Remove Line 350 ngx-drag-scroll.ts 
`this.resetScrollLocation();
`

**Comment by bfwg** [comment]
The change is in 1.7.8. Thanks.
