### ISSUE TITLE
While executing the code  getting the error 

### ISSUE THREAD

**Issue by ramyalatha-redpinesignals** [bfwg/ngx-drag-scroll#134]
ERROR in Error: Metadata version mismatch for module <path>

/node_modules/ngx-drag-scroll/index.d.ts, found version 4, expected 3, resolving symbol UiModule in <path>/src/app/pages/ui/ui.module.ts, resolving symbol UiModule in <path>/src/app/pages/ui/ui.module.ts
    at syntaxError (<path>\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (<path>\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
    at StaticReflector.simplify (<path>\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
    at StaticReflector.annotations (<path>\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
    at _getNgModuleMetadata (<path>node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (<path>\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at includeLazyRouteAndSubRoutes (<path>\node_modules\@angular\compiler-cli\src\ngtools_impl.js:66:25)
    at Array.reduce (<anonymous>)
    at includeLazyRouteAndSubRoutes (<path>\node_modules\@angular\compiler-cli\src\ngtools_impl.js:67:26)
    at Array.reduce (<anonymous>)
    at Object.listLazyRoutesOfModule (<path>\node_modules\@angular\compiler-cli\src\ngtools_impl.js:54:36)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (<path>i\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (<path>\node_modules\@ngtools\webpack\src\plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (<path>\node_modules\@ngtools\webpack\src\plugin.js:495:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

This is package.json file
{
  "name": "",
  "version": "1.1.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0 --disable-host-check",
    "build": "ng build --base-href=\"./\"",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "install": "napa"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^4.3.0",
    "@angular/common": "^4.3.0",
    "@angular/compiler": "^4.3.6",
    "@angular/compiler-cli": "^4.3.0",
    "@angular/core": "^4.3.0",
    "@angular/forms": "^4.3.0",
    "@angular/http": "^4.3.0",
    "@angular/platform-browser": "^4.3.0",
    "@angular/platform-browser-dynamic": "^4.3.0",
    "@angular/platform-server": "^4.3.0",
    "@angular/router": "^4.3.0",
    "@asymmetrik/ngx-leaflet": "^2.5.1",
    "@ng-idle/core": "2.0.0-beta.12",
    "@ng-idle/keepalive": "2.0.0-beta.12",
    "@swimlane/ngx-charts": "^6.0.2",
    "@types/es6-shim": "^0.31.32",
    "@types/geojson": "1.0.1",
    "@types/jquery": "^2.0.41",
    "@types/leaflet": "1.2.1",
    "@types/node": "^7.0.12",
    "alasql": "^0.4.2",
    "angular-2-dropdown-multiselect": "1.6.3",
    "angular2-datatable": "0.6.0",
    "angular2-google-maps": "0.17.0",
    "angular2-jwt": "^0.2.3",
    "angular2-moment": "^1.0.0-beta.rc.1",
    "angular2-mqtt": "^1.7.1",
    "angular2-toaster": "^4.0.1",
    "angular2-websocket": "^0.9.5",
    "awesome-bootstrap-checkbox": "1.0.0-alpha.4",
    "bootstrap": "4.0.0-alpha.6",
    "chart.js": "2.5.0",
    "core-js": "2.4.1",
    "d3": "^4.10.2",
    "datamaps": "0.5.8",
    "dropzone": "4.3.0",
    "font-awesome": "4.7.0",
    "fullcalendar": "3.2.0",
    "jquery": "^3.1.1",
    "jquery-knob": "1.2.11",
    "jquery-slimscroll": "1.3.8",
    "jquery-ui-dist": "1.12.1",
    "jwt-decode": "^2.2.0",
    "leaflet": "^1.2.0",
    "leaflet-map": "^0.2.1",
    "leaflet.vectorgrid": "^1.2.0",
    "metrojs": "0.9.77",
    "moment": "2.17.1",
    "mydatepicker": "^2.0.31",
    "mydaterangepicker": "^4.2.0",
    "ng2-carouselamos": "^3.2.0",
    "ng2-charts": "1.5.0",
    "ng2-ckeditor": "1.1.6",
    "ng2-dragula": "^1.5.0",
    "ng2-popover": "0.0.14",
    "ng2-stomp-service": "^1.2.2",
    "ngx-bootstrap": "^1.8.1",
    "ngx-drag-scroll": "^1.5.1",
    "ngx-modialog": "^3.0.4",
    "react-leaflet-markercluster": "^1.1.6",
    "rxjs": "^5.5.2",
    "socicon": "3.0.4",
    "sockjs-client": "^1.1.4",
    "stompjs": "^2.3.3",
    "sweetalert2": "7.17.0",
    "tether": "1.4.0",
    "topojson": "2.2.0",
    "ts-helpers": "1.1.1",
    "typescript": "^2.4.0",
    "underscore": "^1.8.3",
    "widgster": "0.0.3",
    "xlsx": "^0.11.3",
    "zone.js": "0.8.5"
  },
  "napa": {
    "pace": "https://github.com/HubSpot/pace.git#v0.7.1",
    "skycons": "https://github.com/darkskyapp/skycons.git#7095ecf5f653dbcadbddb0d317b42e65fe091eae"
  },
  "devDependencies": {
    "@angular-devkit/core": "0.0.29",
    "@angular/cli": "1.6.1",
    "@angular/compiler-cli": "4.0.1",
    "@types/core-js": "0.9.41",
    "@types/d3": "^4.10.0",
    "@types/jasmine": "2.5.47",
    "@types/jquery": "2.0.41",
    "@types/jquery.slimscroll": "1.3.30",
    "@types/node": "7.0.12",
    "codelyzer": "2.0.1",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.4.1",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "0.2.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "napa": "2.3.0",
    "protractor": "5.1.1",
    "sass-to-js": "1.3.0",
    "ts-node": "3.0.2",
    "tslint": "5.0.0",
    "typescript": "2.2.2"
  }
}

**Comment by bfwg** [comment]
ngx-drag-scroll supports Angular 5+, please update the angular version and test again. 

Thanks.

**Comment by ramyalatha-redpinesignals** [comment]
If i upgrade angular 5+  then the other dependencies which are using getting error . So I want the package which will support angular 4 along with this functionality .

**Comment by bfwg** [comment]
You can install 1.4.2, I believe it supports ng4.

**Comment by ramyalatha-redpinesignals** [comment]
@bfwg Still have an issue with 1.4.2 also
