### ISSUE TITLE
angular6 support

### ISSUE THREAD

**Issue by realgsong** [bfwg/ngx-drag-scroll#138]
* **I'm submitting a ...**
  - [ V ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Reporting bug

* **What is the current behavior?**
npm show error while building with ng6
```
npm ERR! peer dep missing: @angular/common@5.2.7, required by ngx-drag-scroll@1.7.9
npm ERR! peer dep missing: @angular/compiler@5.2.7, required by ngx-drag-scroll@1.7.9
npm ERR! peer dep missing: @angular/core@5.2.7, required by ngx-drag-scroll@1.7.9

```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**  you can use the demo site as an example or via https://plnkr.co
1. Install and generate boilerplate project of angular 6
1. npm install ngx-drag-scroll --save
1. npm ls

* **What is the expected behavior?**
No dep error.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 1.7.9
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bfwg** [comment]
@realgsong I'm on it, thanks for reproting.

**Comment by bfwg** [comment]
Please try 1.8.0
