### ISSUE TITLE
Different behavior on different platforms

### ISSUE THREAD

**Issue by MortezaT** [bfwg/ngx-drag-scroll#140]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

I've created and app which uses several drag-scroll components for scrolling horizontally in a pretty long `RTL` page which only scrolls vertically, but the behavior is completely different in Google Chrome `Desktop`, `Android`, and `iOS`.
In desktop it works ad expected without any problems.
On iOS, while scrolling the page (vertically) the drag-scroll components suddenly rest their position to start and sometimes they retain their position after a while.
On Android, in addition to the iOS problem on scroll, the reset moves the position to the end of component where the show more button located.

here is the `ng version` output:

    Angular CLI: 1.7.4
    Node: 8.11.1
    OS: linux x64
    Angular: 5.2.10
    ... animations, common, compiler, compiler-cli, core, forms
    ... http, language-service, platform-browser
    ... platform-browser-dynamic, platform-server, router
    ... service-worker

    @angular/cdk: 5.2.1
    @angular/cli: 1.7.4
    @angular/material: 5.2.1
    @angular-devkit/build-optimizer: 0.3.2
    @angular-devkit/core: 0.3.2
    @angular-devkit/schematics: 0.3.2
    @ngtools/json-schema: 1.2.0
    @ngtools/webpack: 1.10.2
    @schematics/angular: 0.3.2
    @schematics/package-update: 0.3.2
    typescript: 2.6.2
    webpack: 3.11.0

**Comment by bfwg** [comment]
Thanks for reporting @MortezaT , I'll look into it.

**Comment by bfwg** [comment]
Hi @MortezaT , can you provide me with a plunker? I want to see how you use the library for your vertical carousel.

**Comment by MortezaT** [comment]
I'm pretty busy right away, but if it helps here is the [page](https://alounak.com/search?page=0&size=9&sort=3&dealType=2&fileType=%20&minNumberOfBedrooms=%20&regionLevel=2&) I'm using your component for mobile phones or any small screens.

**Comment by bfwg** [comment]
The issue should be resolved in the latest version(1.8.1). Sorry for the delay. I was swamped with work.

**Comment by MortezaT** [comment]
It's working really good. Thank for the rapid response :)
