### ISSUE TITLE
Does not work with Angular 6

### ISSUE THREAD

**Issue by MrSnappingTurtle** [bfwg/ngx-drag-scroll#141]
* **I'm submitting a ...**
  - [x ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

Currently, the images wrap onto new lines instead of being hidden inside the carousel. This code was functioning before we upgraded to Ng6 and thus from `angular2-drag-scroll` to `ngx-drag-scroll`. I've looked at the latest project, and it doesn't seem like the directives changed.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**  you can use the demo site as an example or via https://plnkr.co

```
<div
    *ngIf="soloView"
    class="mobile-photos-container"
    drag-scroll
    fxShow
    fxHide.gt-sm>
    <img
        *ngFor="let photo of photos"
        src="{{photo?.url}}"
        alt="Item Picture">
</div>
```

Results in the following:

![screen shot 2018-06-04 at 3 18 00 pm](https://user-images.githubusercontent.com/8148243/40944684-88f3a1da-680a-11e8-9a09-6f4382f52270.png)

* **Please tell us about your environment:**
  
  Latest `ngx-drag-scroll`, Angular 6, and latest Chrome.

**Comment by MrSnappingTurtle** [comment]
Please let me know if you'd like me to try anything out or test.

**Comment by bfwg** [comment]
Hi @MrSnappingTurtle , can you try to test without the flexLayout attributes and user `dragScroll` instead of `drag-scroll`?
```
<div
    *ngIf="soloView"
    class="mobile-photos-container"
    dragScroll>
    <img
        *ngFor="let photo of photos"
        src="{{photo?.url}}"
        alt="Item Picture">
</div>
```

**Comment by MrSnappingTurtle** [comment]
I'll try it out later today and will let you know.

**Comment by MrSnappingTurtle** [comment]
Ah, it's `dragScroll` now. Didn't notice that changed when I looked at the npm page, sorry. All works now.

Thanks for your help! :)

**Comment by bfwg** [comment]
No problem. Glad I can help.
