### ISSUE TITLE
ng build --prod [name]

### ISSUE THREAD

**Issue by danielhanzs** [bfwg/ngx-drag-scroll#147]
* **I'm submitting a ...**
  - [ x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
When I wanted to build the library (angular cli 6) I got this error message, in runtime with ng serve it's working like charm.

projects\epg\src\lib\epg-date-manager\epg-date-manager.component.ts.EpgDateManagerComponent.html(5,1): : Directive DragScrollDirect
ive, Expected 0 arguments, but got 1.

Error: projects\epg\src\lib\epg-date-manager\epg-date-manager.component.ts.EpgDateManagerComponent.html(5,1): : Directive DragScrol
lDirective, Expected 0 arguments, but got 1.

    at Object.<anonymous> (D:\streaming-lego-admin\web-lego\node_modules\ng-packagr\lib\ngc\compile-source-files.js:53:68)
    at Generator.next (<anonymous>)
    at D:\streaming-lego-admin\web-lego\node_modules\ng-packagr\lib\ngc\compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (D:\streaming-lego-admin\web-lego\node_modules\ng-packagr\lib\ngc\compile-source-files.js:3:12)
    at Object.compileSourceFiles (D:\streaming-lego-admin\web-lego\node_modules\ng-packagr\lib\ngc\compile-source-files.js:19:12)
    at Object.<anonymous> (D:\streaming-lego-admin\web-lego\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.
js:26:32)
    at Generator.next (<anonymous>)
    at D:\streaming-lego-admin\web-lego\node_modules\ng-packagr\lib\ng-v5\entry-point\ts\compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**  you can use the demo site as an example or via https://plnkr.co
- Fresh angular cli project
- Created a library named epg
- Added the ngx-drag-scroll to the lib package.json
- Added dragScroll to html element
- ng run epg:build or ng build --prod epg

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: latest
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bfwg** [comment]
HI, @danielhanzs . I'll take a looking over the weekend. Thanks for reporting.

**Comment by MortezaT** [comment]
@danielhanzs 
Can you provide some code sample?

**Comment by danielhanzs** [comment]
sorry, in the meantime I wrote an rxjs based drag scroll, but the code at fault is 

@HostListener('window:resize', ['$event'])
  onResize() {
    this.markElDimension();
    this.checkNavStatus();
  }

you need to delete the $event at HostListener line of add the event at the onResize function.

After that it should build without errors
