### ISSUE TITLE
'drag-scroll' is not a known element

### ISSUE THREAD

**Issue by prajaktatkare1234** [bfwg/ngx-drag-scroll#153]
I am getting the below error when I am using the drag-scroll element in any component.html
"'drag-scroll' is not a known element"
I have imported it into app.module.ts.Is there any need to import in component.ts file?
If yes, then what should I import?

**Comment by IlCallo** [comment]
How did you resolved this?

**Comment by MNorgren** [comment]
I experience the same thing. VSCode gives me an error message, but everything compiles and runs just fine.   Annoying, but not really worth investing much time into

**Comment by alpersilistre** [comment]
Unfortunately, I am having the same issue. I tried to use it as an inline template as well but no luck.
