### ISSUE TITLE
[Bug] Could not find a declaration file for module 'ngx-drag-scroll'

### ISSUE THREAD

**Issue by IlCallo** [bfwg/ngx-drag-scroll#156]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
```
error TS7016: Could not find a declaration file for module 'ngx-drag-scroll'. '.../node_modules/ngx-drag-scroll/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/ngx-drag-scroll` if it exists or add a new declaration (.d.ts) file containing `declare module 'ngx-drag-scroll';`
```
This pops out after the installation when I try to compile, **even if there is a .d.ts file**.
There are also some "peer dipendency mismatch" warnings.

* **Please tell us about your environment:**  
  - Version: 2.0.0-beta.3
  - Angular: 6.0.9

**Comment by bfwg** [comment]
HI @IlCallo I was not able to reproduce the error. 
I did `ng new` to create a new project with angular cli 6.0.8, and imported the ngx-drag-scroll module.
The application was running without any error for me.

Can you try with 6.0,8? If the issue goes away I will look into 6.0.9. If not, please provide me with more information(OS version, node version etc.)

**Comment by IlCallo** [comment]
Don't have much time atm, will try as soon as I can and report back.
My environment:
- Windows 10
- Node 9.3.0

Need other env informations?

**Comment by bfwg** [comment]
hi @IlCallo , have you tried 6.0.8?

**Comment by IlCallo** [comment]
Sorry for delay.
In the meantime I switched to angular material experimental drag&drop to keep external dependencies to bare minimum.
If no one else experienced the same problem it probably was only on my setup, you can close this, ty for your time :)

**Comment by bfwg** [comment]
No problem 😄

**Comment by mrachwal** [comment]
I'm also facing this issue. Angular 7.1.4. In console I'm getting:
![image](https://user-images.githubusercontent.com/29977336/52636959-3e027580-2ece-11e9-9e56-4a8a1590857c.png)

**Comment by retkpop** [comment]
@bfwg  Not support Angular 8+ ?

<img src="https://i.imgur.com/31h8Ywd.png" style="width: 100%"/>

**Comment by bfwg** [comment]
I'm currently working on the hotfix.

**Comment by bfwg** [comment]
@retkpop can you try 9.0.0-beta.2?

**Comment by retkpop** [comment]
> @retkpop can you try 9.0.0-beta.2?
@bfwg thank u. It working

**Comment by BizzottoClaudio** [comment]
I have the same problem (i'm on windows).
Upgrading from angular 8 to angular 9 and using "ngx-drag-scroll": "^9.0.0-beta.4"
The import still cannot be found.
Also i see that this repo hase the last release on 6 Jun - 9.0.0-beta.2 but on NPM the latest is 9.0.0-beta.4 and has been release 3 month ago
