### ISSUE TITLE
Angular universal error on compiling

### ISSUE THREAD

**Issue by matteobarale** [bfwg/ngx-drag-scroll#158]
* **I'm submitting a ...**
  - [*] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

During compiling of my app there is this error
ERROR in server.js from UglifyJs
Unexpected token: name (DragScrollItemDirective) [server.js:12097,6]

Please tell us about your environment:
        Version: 2.0.0-beta.3
        Angular: 5.0.3

**Comment by bfwg** [comment]
Hi @matteobarale , sorry for the late reply. This library does not support Angular Universal at the moment. One thing you can try is to upgrade your project to Angular 6.x.x. If that does not work, a PR is more than welcome. 

Thanks!
