### ISSUE TITLE
Text is inline and can't seem to be changed

### ISSUE THREAD

**Issue by JonasJW** [bfwg/ngx-drag-scroll#164]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

report bug

* **What is the current behavior?**

Every paragraph and probably any other text element is inline. I tried to have cards with text in it but the look like this:
<img width="1388" alt="bildschirmfoto 2018-08-09 um 22 17 14" src="https://user-images.githubusercontent.com/38528004/43923443-0d499e6c-9c22-11e8-8f56-ba5461ca8875.png">

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**  you can use the demo site as an example or via https://plnkr.co

For some reason I cant post HTML code here so I will have to add screenshots.

This is the card code:

<img width="808" alt="bildschirmfoto 2018-08-09 um 22 20 32" src="https://user-images.githubusercontent.com/38528004/43923605-900b6c54-9c22-11e8-9686-6e5bda0f3576.png">

And this is the actual carousel
<img width="500" alt="bildschirmfoto 2018-08-09 um 22 20 35" src="https://user-images.githubusercontent.com/38528004/43923614-984da1a2-9c22-11e8-9211-ac515c2ae045.png">

* **What is the expected behavior?**

having the paragaph text inside the borders of the card and not inline

* **What is the motivation / use case for changing the behavior?**
...

* **Please tell us about your environment:**
  
  - Version: 1.0.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bfwg** [comment]
Hi @JonasJW , please add the below CSS to your item elements.
```
  vertical-align: top;
  word-wrap: break-word;
  white-space: normal;

```

Please let me know if you have more questions.
