### ISSUE TITLE
cannot reset (no entry point)

### ISSUE THREAD

**Issue by phil123456** [bfwg/ngx-drag-scroll#167]
* **I'm submitting a ...**
  - [ ] bug report
  - [ x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

feature

* **What is the current behavior?**

no function to reset the component to the first element
no function to move to nth component
so far I use for loops (but no way to know nativeley how many elements are in the component)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**  you can use the demo site as an example or via https://plnkr.co

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

obvious missing functionality

* **Please tell us about your environment:**
  
  - Version: 1.0.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bfwg** [comment]
You can use the `moveTo` method to navigate to nth element.
https://github.com/bfwg/ngx-drag-scroll/blob/develop/src/ngx-drag-scroll.ts#L308

Let me know if you have more questions and I can reopen the issue.

Thanks.

**Comment by phil123456** [comment]
this makes no sense...your comp should make our dev life easier, 
using moveto scrolls the component in a visible manner, I have to hide it not to show this behaviour

at least create an entry point to know how many elements are in the component

we decided to use something else anyway 

this is really a low level component that barely does display divs with a scroll bar and dont offer much convenience

regards
