### ISSUE TITLE
right click and left click not working  (drag is working)

### ISSUE THREAD

**Issue by kvimalkr55** [bfwg/ngx-drag-scroll#174]
<drag-scroll class="demo-one" drag-scroll-y-disabled="true" scrollbar-hidden="true" fxLayoutGap="10px"
            (reachesLeftBound)="leftBoundStat($event)" (reachesRightBound)="rightBoundStat($event)" #nav>

            <div drag-scroll-item class="col-md-4" *ngFor="let userData of userDatas">
              <div class="px-4">
                <img [src]="userData.img" class="rounded-circle img-center img-fluid shadow shadow-lg--hover" style="width: 200px;">
                <div class="pt-4 text-center">
                  <h5 class="title">
                    <span class="d-block mb-1">{{userData.name}} </span>
                    <small class="h6 text-muted">Professor</small>
                  </h5>
                  <div class="mt-3">
                    <a href="https://demos.creative-tim.com/argon-design-system/examples/landing.html#" class="btn btn-warning btn-icon-only rounded-circle">
                      <i class="fa fa-twitter"></i>
                    </a>
                    <a href="https://demos.creative-tim.com/argon-design-system/examples/landing.html#" class="btn btn-warning btn-icon-only rounded-circle">
                      <i class="fa fa-facebook"></i>
                    </a>
                    <a href="https://demos.creative-tim.com/argon-design-system/examples/landing.html#" class="btn btn-warning btn-icon-only rounded-circle">
                      <i class="fa fa-dribbble"></i>
                    </a>
                  </div>
                </div>
              </div>
            </div>

      </drag-scroll>

      <button (click)="moveLeft()" class="btn left"><i class="fas fa-chevron-left"></i></button>
      <button (click)="moveRight()" class="btn right"><i class="fas fa-chevron-right"></i></button>

**Comment by IvanPrat** [comment]
Same to me.

It seems it's because the animation.

You can look at this reference, and check for the code: /node_modules/ngx-drag-scroll/lib/ngx-drag-scroll.js:196. If you go to `DragScrollComponent.prototype.moveLeft` and you remove `this.isAnimation`, you will notice it actually works as expected. 

However, don't do this. Just wait for the author's fix.

**Comment by bfwg** [comment]
Relate to #176

**Comment by bfwg** [comment]
Please try 2.0.1 Thanks.

**Comment by bfwg** [comment]
Hi @kvimalkr55 , can you give 2.0.2 a try? Thanks
