### ISSUE TITLE
Move Right randomly fails 

### ISSUE THREAD

**Issue by anoopsurendrananp** [bfwg/ngx-drag-scroll#177]
Hi I installed ngx-drag-scroll@2.0.1. 
It worked fine with some 5 elements pretty good.
But when I added navigation left and right buttons. The event is correctly triggering but at certain points, moveRight is not reflected in DOM.

This is a demo http://www.cedextech.com/test/chat-ui/ghh
click on chat icon
Click I accept
Click Get started
You can see a group of buutons are listing
If you check on the console, upon clicking right button first 3-4 clicks work fine, but in certain cases I have to click twice to move right.

The my component.html contain 
 ```
<div>
          <button class="navbtns" (click)="moveLeft()"><i class="fa fa-angle-left" aria-hidden="true"></i></button>
          <drag-scroll #nav scrollbar-hidden="true" drag-scroll-y-disabled="true">
            <button *ngFor="let quickReply of chat.buttons" type="button" drag-scroll-item (click)="onClick(quickReply.text, quickReply.value, null)"
              class="btn btn-outline">
              {{quickReply.text}}
            </button>
          </drag-scroll>
          <button class="navbtns" (click)="moveRight()"><i class="fa fa-angle-right" aria-hidden="true"></i></button>
        </div>
```

**Comment by bfwg** [comment]
hi @anoopsurendrananp , can you give 2.0.2 a shot?

**Comment by anoopsurendrananp** [comment]
@bfwg Thank you so much for the response.
It works perfect
