### ISSUE TITLE
Enable virtual scroll

### ISSUE THREAD

**Issue by Belouccio** [bfwg/ngx-drag-scroll#178]
Hi. Thank you for your work! Can you include virtual scroll into drag-scroll? Each my drag-scroll-item element contains a thousand items, so there are a lot of them in the DOM. It will be great if you do this, or tell me how can i do it by myself))

**Comment by bfwg** [comment]
Hi @Belouccio , have you tried to make the carousel array elements dynamic? You can try to remove/append elements on scroll/drag.
