### ISSUE TITLE
Demo website not opening

### ISSUE THREAD

**Issue by kartikjagdale** [bfwg/ngx-drag-scroll#180]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**

When I click on demo link it takes me to a page where the demo is not being shown only empty page 
where a welcome message is being shown. Upon Inspecting I found in console.:
```
core.js:1601 ERROR Error: Uncaught (in promise): SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://bfwg.github.io/ngx-drag-scroll/' cannot be created in a document with origin 'https://fanjin.io' and URL 'https://fanjin.io/ngx-drag-scroll/'.
Error: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://bfwg.github.io/ngx-drag-scroll/' cannot be created in a document with origin 'https://fanjin.io' and URL 'https://fanjin.io/ngx-drag-scroll/'.
```
* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**  you can use the demo site as an example or via https://plnkr.co

* **What is the expected behavior?**

Demo website should be opened successfully

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 1.0.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by bfwg** [comment]
It is up and running now, thanks for reporting.
