### ISSUE TITLE
dragscroll is lagging on mobile device

### ISSUE THREAD

**Issue by Andi1990** [bfwg/ngx-drag-scroll#183]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
When scrolling through content by swiping on a mobile device there is a lag (<1s) between "swipe-end" and snap to the next list item. When scrolling on a desktop device no lag can be observed. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
The behavior can be reproduced by simply loading the demo page on a mobile device and scrolling through swipe actions.
Oddly, when scrolling on a desktop but emulating a mobile device with Chrome's Device Mode's screen emulator, the same lag can be observed!

* **What is the expected behavior?**
Expected behavior would be no lag on mobile devices.

* **What is the motivation / use case for changing the behavior?**
Smoother operation on mobile devices.

* **Please tell us about your environment:**
  
  - Version: 2.0.2
  - Browser: Mobile Chrome
  - Device: Samsung Galaxy S7

**Comment by bfwg** [comment]
Resolved in #190
