### ISSUE TITLE
Add an @Output for once the drag-scroll has been initialised

### ISSUE THREAD

**Issue by DronkWynie** [bfwg/ngx-drag-scroll#185]
* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
New Feature

* **What is the current behavior?**
There's no way to detect once drag-scroll has been initialised

* **What is the expected behavior?**
Add an **@Output** for once the drag-scroll has been initialised

* **What is the motivation / use case for changing the behavior?**
If there is an if check around the component, there is no way to know when the drag-scroll has been initialized.

**Comment by bfwg** [comment]
Resolved in #192
