### ISSUE TITLE
error in console when only two images and click right button

### ISSUE THREAD

**Issue by Paul75** [bfwg/ngx-drag-scroll#186]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Click into writ button (like exemple) it say errors when have only two images ...

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**  you can use the demo site as an example or via https://plnkr.co
Only create carousel with two image or one and make a button and if I click right it crach
Exemple : https://stackblitz.com/edit/angular-7csph3

* **Please tell us about your environment:**
    - Version: 1.0.0
  - Browser: [all]

**Comment by bfwg** [comment]
@Paul75 the correct way is to set a `width` to the `img`s, not `min-width`. Let me know if it doesn't work for you and I can reopen this.
