### ISSUE TITLE
Content gone within the <drag-scroll> tag

### ISSUE THREAD

**Issue by jasperltz93** [bfwg/ngx-drag-scroll#194]
* **I'm submitting a ...**
  - [x ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
![image](https://user-images.githubusercontent.com/26257150/49802267-67e0d400-fd87-11e8-8809-ddd78842249f.png)
A div generated by the library with a "drag-scroll-content" class is having 0px width and height, which causes all my content disappear

* **What is the expected behavior?**
Remove the width and height style, then it should be fine, there is a workaround which i need to overwrite the style, and it seems troublesome

* **What is the motivation / use case for changing the behavior?**
So that we no need to write another style to overwrite it

* **Please tell us about your environment:**
  

  - Version: 2.0.4
  - Browser: [ Chrome 70.0.3538.110 ]

**Comment by bfwg** [comment]
Hi, have you tried setup a width and height for your drag-scroll component? The “drag-scroll-content” takes its width and height from the parent.
