### ISSUE TITLE
right and left

### ISSUE THREAD

**Issue by bentzibentz** [bfwg/ngx-drag-scroll#196]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Click right and left not working, always get the following error:
```
ERROR TypeError: Cannot read property '_elementRef' of undefined at DragScrollComponent.push../node_modules/ngx-drag-scroll/lib/ngx-drag-scroll.js.DragScrollComponent.maximumIndex (ngx-drag-scroll.js:432) at DragScrollComponent.push../node_modules/ngx-drag-scroll/lib/ngx-drag-scroll.js.DragScrollComponent.moveRight (ngx-drag-scroll.js:204) at HomeComponent.push../src/app/pages/home/home.component.ts.HomeComponent.moveRight (home.component.ts:137)
```
indexChanged is also never called.

Implementation is the same like in the demo for demo-one

* **Please tell us about your environment:**
Angular 7.1.0
  
  - Version: 2.0.4
  - Browser: all on OSX

**Comment by bfwg** [comment]
Hi, can you give 2.1.1 a try? I added Angular 7 support.

**Comment by bentzibentz** [comment]
Hi, unfortunately the error is still there:

```
HomeComponent.html:33 ERROR TypeError: Cannot read property '_elementRef' of undefined
    at DragScrollComponent.push../node_modules/ngx-drag-scroll/lib/ngx-drag-scroll.js.DragScrollComponent.maximumIndex (ngx-drag-scroll.js:434)
    at DragScrollComponent.push../node_modules/ngx-drag-scroll/lib/ngx-drag-scroll.js.DragScrollComponent.moveRight (ngx-drag-scroll.js:204)
    at HomeComponent.push../src/app/pages/home/home.component.ts.HomeComponent.moveRight (home.component.ts:139)
```

**Comment by bfwg** [comment]
I think what happen is that your control button can not get hold of the carousel element. Can you try to put them in the same parent element and load them at once?

**Comment by Arley-Fernandez-Taximo** [comment]
Please any solution for this issue.

**Comment by bfwg** [comment]
@Arley-Fernandez-Taximo Can you reproduce the bug with the demo project? I cannot reproduce the issue.

**Comment by Arley-Fernandez-Taximo** [comment]
I tried to made a universal component for simplify the use in many other components.

# Any component
```
<app-draggable>
      <div drag-scroll-item style="width: 100%; height: 100%">1</div>
      <div drag-scroll-item style="width: 100%; height: 100%">2</div>
      <div drag-scroll-item style="width: 100%; height: 100%">3</div>
</app-draggable>
```

# Draggable component
```
<drag-scroll style="width: auto; height: 40vh" [drag-scroll-disabled]="true">
  <ng-content></ng-content>
</drag-scroll>

<div class="draggable-button-container col-12">
  <div class="col-6">
    <button (click)="moveLeft()" class="draggable-button float-left">
      <
    </button>
  </div>
  <div class="col-6">
    <button (click)="moveRight()" class="draggable-button float-right">
      >
    </button>
  </div>
</div>
```
# Draggable.ts
```
  @ViewChild(DragScrollComponent) ds: DragScrollComponent;

  moveLeft() {
    this.ds.moveLeft();
  }

  moveRight() {
    this.ds.moveRight();
  }
```

**Comment by Arley-Fernandez-Taximo** [comment]
Any solution for this issue.

**Comment by bfwg** [comment]
Hi @Arley-Fernandez-Taximo , I'm on my vacation and I've looked into the issue with ng-content. Sadly I can't make the library to support ng-content in a short time. You can try to remove the ng-content and pass the data into `app-draggable` and create `drag-scroll-item` inside `app-draggable` as a workaround.

**Comment by bfwg** [comment]
Duplicated of #207
