### ISSUE TITLE
Error during template compile of 'DragScrollModule'

### ISSUE THREAD

**Issue by swapnil-coditas** [bfwg/ngx-drag-scroll#198]
I am getting "Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'." while ng build

Below is my package.json

`"dependencies": {
		"@angular/animations": "7.1.4",
		"@angular/cdk": "7.0.1",
		"@angular/common": "7.1.4",
		"@angular/compiler": "7.1.4",
		"@angular/core": "7.1.4",
		"@angular/forms": "7.1.4",
		"@angular/http": "7.1.4",
		"@angular/platform-browser": "7.1.4",
		"@angular/platform-browser-dynamic": "7.1.4",
		"@angular/platform-server": "7.1.4",
		"@angular/router": "7.1.4",
		"@ngx-pwa/local-storage": "7.0.0",
		"chart.js": "2.7.1",
		"classlist.js": "1.1.20150312",
		"core-js": "2.5.7",
		"lodash.differencewith": "4.5.0",
		"lodash.isequal": "4.5.0",
		"ngx-drag-scroll": "2.1.1",
		"typescript": ">=3.1.1 <3.2",
		"zone.js": "0.8.26"
	},
	"devDependencies": {
		"@angular-devkit/build-angular": "0.11.4",
		"@angular-devkit/core": "7.0.1",
		"@angular/cli": "7.1.4",
		"@angular/compiler-cli": "7.1.4",
		"@angular/language-service": "7.1.4",		
		"@types/node": "6.0.60",
		"codelyzer": "^4.5.0"
	}`

**Comment by ctinach** [comment]
Same here. Any solution?

**Comment by bfwg** [comment]
@swapnil-coditas can you provide the Angular version?

**Comment by swapnil-coditas** [comment]
Using Angular 7.1.4

**Comment by swapnil-coditas** [comment]
Thanks a lot @bfwg 

Just need to replace 

> import { DragScrollDirective } from 'ngx-drag-scroll';

with 

> import { DragScrollComponent } from 'ngx-drag-scroll';
