### ISSUE TITLE
Cannot redeclare block-scoped variable 'ngDevMode'. 

### ISSUE THREAD

**Issue by IlCallo** [bfwg/ngx-drag-scroll#199]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

Compile error is given when using the library with Angular 7.2 and TS 3.2

`ERROR in ../node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'. `

* **What is the expected behavior?**

It should work

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

This is probably due to the fact that you set `@angular/core` and the other 3 as dependencies instead of peer dependencies.

By doing this, when installing with yarn, for some reason `@angular/core` versions won't match between the one your library is requesting and the one requested by the project, effectively downloading two `@angular/core` and resulting in a duplicate `ngDevMode` declaration.

Moving direct dependencies to peerDependencies (given that they are basic dependencies automatically included in every angular installation) should do the trick I guess.

**Comment by bfwg** [comment]
@IlCallo would you like to create a PR for this? I feel you have more knowledge in this area.

**Comment by IlCallo** [comment]
A new angular documentation page have been added to address "how to create a library" topic, and the procedure I suggested is better explained there now.

https://next.angular.io/guide/creating-libraries#use-typescript-path-mapping-for-peer-dependencies

**Comment by IlCallo** [comment]
Expanding on previous post, the solution should be as simple as removing

    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/core": "^7.0.0",
    "tsickle": "^0.33.0"

from `dependencies`, and adding them to both `peerDependencies` and `devDependencies`.
