### ISSUE TITLE
Max index of drag-scroll-item

### ISSUE THREAD

**Issue by fferaud** [bfwg/ngx-drag-scroll#202]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
To be able to know the mx current index

* **What is the current behavior?**
The `(indexChanged)` event allows to get the current index. The `moveTo(index)` method allows to move to the element with index position.

But we can't to know the max index to be able to do `moveTo(index+x)` or `moveTo(index-x)` and speed up moving. If we move to an index out of bound the behavior is a bit random so it would be better if we could test the maximum index.

I ask you this feature because in my implementations for 25 elements the max index is 18 and I do not know if it is possible to calculate this difference (my elements have a variable size)

If it's already possible i apologize :(

Thanks for reading

* **Please tell us about your environment:**
  
  - Version: latest
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView]

**Comment by bfwg** [comment]
Hi @fferaud , I've added an `indexBound` attribute in 7.1.0 which should give you the max index allowed to the given container.
