### ISSUE TITLE
Tooltip alignment issues after scroll

### ISSUE THREAD

**Issue by mailmrmanoj** [bfwg/ngx-drag-scroll#203]
I have a list of items that I plot using ngx-drag-scroll and on hovering of each number I'm displaying a custom tooltip based on the condition when the hovered number matches with the variable defined in controller.

![image](https://user-images.githubusercontent.com/7077567/51522393-41668c00-1e4f-11e9-8817-2136e432e920.png)

When I hovered on **6** I was able to see the tooltip for the same under **6**. But when I  scrolled through the list and if I hover  the tooltip seems to move away and occupy additional space for each items.

![image](https://user-images.githubusercontent.com/7077567/51522711-0022ac00-1e50-11e9-803e-94a39d036fac.png)

Please find the code here:
```

  <div class="row">
                <div class="col-md-1">
                    <button (click)="moveLeft()">Left</button>
                </div>
                <div class="col-md-10">
                    <drag-scroll #nav>
                        <div drag-scroll-item *ngFor=" let item of  numberedLists;let i=index ">                        
                            <div (mouseenter)=" mouseEnter(item) " (mouseleave)=" mouseLeave(item) ">
                                    <span " class="block percent-blue cursor-pointer">
                  {{i}}</span>
                                <div class=" speech-bubble " *ngIf=" hoveredItem === item.customer_name ">
                                    This is the description for {{i}}
                                  </div>
                            </div>                        
                        </div>
                    </drag-scroll>
                </div>
                <div class=" col-md-1 ">
                    <button (click)=" moveRight() ">Right</button>
                </div>
            </div>

```
Additional Info : 
I've used speech bubble from the following site [https://www.natashatherobot.com/speech-bubble-css/](https://www.natashatherobot.com/speech-bubble-css/)

**Comment by bfwg** [comment]
Hi @mailmrmanoj , this sounds like a compatibility issue, have you tried [Material2 tooltip](https://material.angular.io/components/tooltip/overview)?

**Comment by mailmrmanoj** [comment]
Hi @bfwg  Works with Material2 tooltip.Thanks
