### ISSUE TITLE
Trying to overwrite the drag-scroll-content class properties.

### ISSUE THREAD

**Issue by SaiMadhav9494** [bfwg/ngx-drag-scroll#204]
Hello, I'm trying to overwrite the drag-scroll-content class inside ngx-drag-scroll.js file to style the way that the scrollbar looks. For that I made a few changes by inserting test props in styles metadata of the DragScrollComponent as following,

```
DragScrollComponent.decorators = [
        { type: Component, args: [{
                    selector: 'drag-scroll',
                    template: "\n    <div class=\"drag-scroll-content\" #contentRef>\n      <ng-content></ng-content>\n    </div>\n  ",
                    styles: ["\n    :host {\n      overflow: hidden;\n      display: block;\n    }\n    .drag-scroll-content {\n      height: 100%;\n      overflow: auto;\n      white-space: nowrap;\n    }\n  .drag-scroll-content::-webkit-scrollbar {\n      width: 20px;\n    }\n   .drag-scroll-content::-webkit-scrollbar-track {\n      background: green;\n    }\n"]
                },] },
    ];
```
I'm not sure that if I'm supposed to alter the library but the styles aren't being applied. The scroll bar still looks default.

**Comment by bfwg** [comment]
Make sure you know what you are doing when altering the library. [here] has more information about the `drag-scroll-content` maybe you are doing something wrong.

**Comment by SaiMadhav9494** [comment]
Hi, I was able to hide the scroll bar by adding a wrapper around it, but my concern is to style the default scroll bar the way I want. I have gone through the issue you suggested but I'm still confused on how to get it done. I agree that I did not completely digest the code in the library. Can you suggest me a way to style the scroll bar given by drag-scroll-content??

**Comment by bfwg** [comment]
Please take a look at [this section of the library](https://github.com/bfwg/ngx-drag-scroll/blob/develop/src/ngx-drag-scroll.ts#L201-L213). The `contentRef` component only carries some CSS property from the original element.

**Comment by bfwg** [comment]
I assume you copied the `ngx-drag-scroll` folder from your `node_modules`. What I would do is to fork this repository and make the code change in the `src` folder, you can then build the library by running `npm run ngc`.

**Comment by SaiMadhav9494** [comment]
No I did not do anything rather than following the instructions on how to install and use it.

**Comment by SaiMadhav9494** [comment]
Ok, I'll try to fork the changes I've made previously.
