### ISSUE TITLE
ng-content is broken the actual behavior

### ISSUE THREAD

**Issue by Arley-Fernandez-Taximo** [bfwg/ngx-drag-scroll#207]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

## Basic usage

only for images or static content

```
  <drag-scroll>
    <img drag-scroll-item src="some-url" />
    <img drag-scroll-item src="some-url" />
    <img drag-scroll-item src="some-url" />
  </drag-scroll>
```

## Advance usage

for display any component or dinamic content

```
  <drag-scroll>
       <ng-content></ng-content>
  </drag-scroll>
```

* **What is the current behavior?**
The use of the library is limited for use any advanced tecnique  of reuse code for many things.

**Comment by bfwg** [comment]
You need to add `ngProjectAs="drag-scroll-item"` to the ng-content element.
```
<ng-content ngProjectAs="drag-scroll-item"></ng-content>
```
