### ISSUE TITLE
*ngFor div does not appear inside of drag-scroll

### ISSUE THREAD

**Issue by 7ang0** [bfwg/ngx-drag-scroll#208]
-drag-scroll style="height:2.5em;" [scrollbar-hidden]="true"-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-alpha-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-bravo-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-charlie-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-echo-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-foxtrot-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-gamma-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-hector-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-indigo-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-juliet-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-kilo-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-lima-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-moon-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-nebraska-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-oscar-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-paul-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-querty-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-romeo-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-sulfur-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-tango-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-uniform-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-victor-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-whiskey-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-x-ray-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-yosemite-/div-
  -div style="display:inline-block;padding-left:2.5em;padding-right:2.5em;"-zulu-/div-
-/drag-scroll-

 works fine. but:

-drag-scroll style="height:2.5em;" [scrollbar-hidden]="true"-
  -div drag-scroll-item style="display:inline-block; padding:2.5em;" *ngFor="let a of az"-
    {{a}}
  -/div-
-/drag-scroll-

 with az = ["alpha", "bravo", "charlie", "delta", "echo", "foxtrot", "gamma", "hector", "indigo", "lima"] does not 

replaced carats with - because i couldnt get embed code to get past the preview

**Comment by dries11** [comment]
This is the same for me. 
My code looks like
`<drag-scroll scroll-x-wheel-enabled=true scrollbar-hidden=true class="ingredient-bar">
    <div drag-scroll-item *ngFor="let ingredient of ingredients" [className]="ingredient.inStock ? 'in-stock chips' : 'out-of-stock chips'" (click)="navigateToPantry(ingredient)" selected=true>
      <div>{{ingredient.name}}</div>
    </div>
  </drag-scroll>`

ngFor doesn't work with drag scroll scrollbar hidden. I'm still looking on trying to find a workaround for this

**Comment by linjie997** [comment]
I have a similiar issue.
Using a *ngFor to create a component to use as drag-scroll-item and enabling [scrollbar-hidden]="true", the drag-scroll height is set to 0px.

`
<drag-scroll
    [scrollbar-hidden]="true"
    (snapAnimationFinished)="animationFinished()"
    (reachesLeftBound)="leftBoundStat($event)"
    (reachesRightBound)="rightBoundStat($event)"
    [snap-duration]="375">
    <div *ngFor="let item of items"  drag-scroll-item>
      <app-item-cmp
        [item]="item">
      </app-item-cmp>
    </div>
  </drag-scroll>`


As a workaround to hide the scrollbar I just used some css (this works only on Chrome):

`
.drag-scroll {
  ::ng-deep {
    .drag-scroll-content {
      &::-webkit-scrollbar {
        display: none;
      }
    }
  }
}
`

**Comment by shivalipawar** [comment]
I'm facing the issue it doesn't work with nested ngFor items even if its seen that drag scroll item is applied to it as below,

`<app-product-card _ngcontent-lqm-c7="" class="margin__threePercent ng-star-inserted" drag-scroll-item="" fxflex="" _nghost-lqm-c11="" ng-reflect-fx-flex="" ng-reflect-img-src="https://images-na.ssl-images-a" ng-reflect-name="Key-kpz01" style="flex: 1 1 0%; box-sizing: border-box; display: inline-block;"><mat-card _ngcontent-lqm-c11="" class="mat-card" fxlayout="column" fxlayoutalign="center center" ng-reflect-fx-layout="column" ng-reflect-fx-layout-align="center center" style="flex-direction: column; box-sizing: border-box; display: flex; place-content: center; align-items: center;"><img _ngcontent-lqm-c11="" class="mat-card-image" mat-card-image="" src="https://images-na.ssl-images-amazon.com/images/I/41-NMNmXj6L.jpg"><p _ngcontent-lqm-c11="">Key-kpz01</p></mat-card></app-product-card> `

Does anyone have any progress or workarounds of how to get it working?

**Comment by diegomachado1** [comment]
I'm in the same situation. I need to use it with *ngFor.
Does anyone solved this?

**Comment by bfwg** [comment]
The `drag-scroll` component needs a fixed width and height. Can you make a [plnkr](https://plnkr.co) to show me what exactly is going on?

**Comment by AvDemeisen** [comment]
if anyone is having issues hiding the scroll bar when using ngFor, use *ngIf="array.length",  that way drag-scroll wont determine the size of the container prior to the data being loaded.

**Comment by bao-doan** [comment]
> The `drag-scroll` component needs a fixed width and height. Can you make a [plnkr](https://plnkr.co) to show me what exactly is going on?

Thank you! This solution works for me 😊.
(Angular 10.2.4, ngx-drag-scroll 9.0.0-beta.4)

**Comment by stefann01** [comment]
> The `drag-scroll` component needs a fixed width and height. Can you make a [plnkr](https://plnkr.co) to show me what exactly is going on?

This works for me too! Thank you very much.
