### ISSUE TITLE
Image gets cut when hide X scroll

### ISSUE THREAD

**Issue by scavassa91** [bfwg/ngx-drag-scroll#209]
When you set the **hide-x-scroll** to **true** the last image gets cutted.
You can see on this print that I've taken from demo.

![sem titulo](https://user-images.githubusercontent.com/19716895/52811468-54e6ca80-307c-11e9-9442-7bb173db66f9.png)

**Comment by bfwg** [comment]
Thanks for reporting the issue @scavassa91 , I'm actively working on it.

**Comment by bfwg** [comment]
The fix is in 7.1.4. 🎉
