### ISSUE TITLE
Not work in Angular Universal 7.1.4

### ISSUE THREAD

**Issue by levytskyy** [bfwg/ngx-drag-scroll#216]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**  you can use the demo site as an example or via https://plnkr.co

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 1.0.0
  - Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by levytskyy** [comment]
Found solution.
Add to package.json  
"babel-cli": "^6.26.0",
"babel-preset-es2015": "^6.24.1",
and run before build  - "compile_ngx-drag-scroll": "babel node_modules/ngx-drag-scroll/lib -d node_modules/ngx-drag-scroll/lib --presets es2015"

**Comment by bfwg** [comment]
Relates to https://github.com/bfwg/ngx-drag-scroll/issues/195
