### ISSUE TITLE
method moveTo can cause currIndex to enter undesired state

### ISSUE THREAD

**Issue by shuped** [bfwg/ngx-drag-scroll#217]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

Calling `ds.moveTo()` with anything above a value returned by `this.maximumIndex()` can cause the `ds.moveLeft()` method to not move the carousel left. Additionally, calling `ds.moveTo(carousel.length - 1) ` will cause subsequent calls to `ds.moveTo()` to fail.

* **Demo**

https://github.com/shuped/ngx-drag-scroll/commit/7eb824678ad7b20614332666ea088a266e2f39d4

* **What is the expected behavior?**

Calling `ds.moveTo(index)` brings the desired index into view, and subsequent calls to `ds.moveLeft()` or `ds.moveRight()` cause the carousel to move left or right, respectively, and calls to `ds.moveTo(index)` always result in the carousel moving to reasonable places.

* **What is the motivation / use case for changing the behavior?**

`ds.moveTo(carousel.length - 1)` being called one or more times sequentially not causing the component to enter unintuitive states.

* **Please tell us about your environment:**
  
  - Version: 2.0.0-beta4 & 7.1.4
  - Browser: tested on [ Chrome 73 | Safari 12.0.2 ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

It was observed in 2.0.0 that if a scroll event happened after the call to moveTo, that `locateCurrentIndex()` would resolve the currIndex to the index of the left most item in the carousel view, however this is not observed in 7.1.4.

**Comment by bfwg** [comment]
Resolved in #218
