### ISSUE TITLE
Not working with touch-interfaces

### ISSUE THREAD

**Issue by Inf0rmatix** [bfwg/ngx-drag-scroll#226]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
I want to report a bug, and will solve it within the next days.

* **What is the current behavior?**
On mobile devices, implementing ngx-drag-scroll swiping does not work. The issue relates to the event not reading clientX and Y from touchEvents correctly as those hide that property on event.touches[0].clientX instead of event.clientX as it's known from MouseEvents.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**  you can use the demo site as an example or via https://plnkr.co
Implement ngx-drag-scroll, open page on mobile or in firefox with touch-simulation turned on.

* **What is the expected behavior?**
Swiping visual elements works on mobile.

* **What is the motivation / use case for changing the behavior?**
Mobile is important. 

* **Please tell us about your environment:**
  
  - Version: 1.0.0
  - Browser: [ Firefox 66.03 ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I'm gonna fix it myself, should be ready for review within the next week :)

**Comment by bfwg** [comment]
@Inf0rmatix What device are you using? Touch events are working fine on my iOS device.

**Comment by Inf0rmatix** [comment]
I'm using Android.

**Comment by bfwg** [comment]
Thanks!

**Comment by bfwg** [comment]
Resolved in #227

**Comment by bfwg** [comment]
7.3.2 is out with the change.
