### ISSUE TITLE
Prepare for Angular 8

### ISSUE THREAD

**Issue by IlCallo** [bfwg/ngx-drag-scroll#228]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Unknown

* **What is the expected behavior?**
Package should be checked to work with Angular 8, when released (probably by the end of May, it's already in RC).

* **What is the motivation / use case for changing the behavior?**
Ability tu use this package with newer versions

**Comment by bfwg** [comment]
I'm going to upgrade the library to Angular 8 sometime this week.

**Comment by bfwg** [comment]
Resolved in #234

**Comment by IlCallo** [comment]
Shouldn't you tag it as version 8.0.0, given that you switched to following Angular major version some time ago? 🤔
Or so I guessed, given that at a point you jumped from v2 to v7

**Comment by IlCallo** [comment]
Also, have your checked it works even when ivy compiler is turned on?

**Comment by bfwg** [comment]
Not yet, my projects are currently on Anguar 7. Good point about the versioning. I'll do that in the next PR.

**Comment by IlCallo** [comment]
Yeah, no hurry, mines too. I'm just reminding everyone to get ready, to be able to migrade flawlessly later on :P
You should probably re-open the issue until you test this with Ivy, considering that's the major new feature into Angular 8

**Comment by demisx** [comment]
We desperately need this too. Our Angular 8 upgrade effort is on hold until this (awesome) module supports it.

**Comment by bfwg** [comment]
@demisx , do you think you can submit a PR for Angular 8 support? I'm pretty busy at the moment to do the dev work but I will be happy to do the review for you.

**Comment by demisx** [comment]
@bfwg I wish I could. I am a techlead/PM and, unfortunately, do not posses Angular knowledge to be able to help here. 😢

**Comment by MrSnappingTurtle** [comment]
Hey, I've tried upgrading the packages myself but unit tests fail and I don't have the library understanding to fix them. Could you please take a look at my PR and maybe give me a hint as to what to do:

https://github.com/bfwg/ngx-drag-scroll/pull/243

**Comment by bfwg** [comment]
Sure, I'll take a look for you.

**Comment by bfwg** [comment]
I couldn't get the unit tests in #243 to work. Can someone else take a look?

**Comment by bfwg** [comment]
Nvm, I think I got the test fixed.

**Comment by bfwg** [comment]
Resolved in #243
