### ISSUE TITLE
Memory leak with lazy loading

### ISSUE THREAD

**Issue by jneves92** [bfwg/ngx-drag-scroll#247]
* **I'm submitting a ...**
  - [x ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

attachment contains the source code and an explanatory video

Video: https://streamable.com/a930i

[DragScrollLeak.zip](https://github.com/bfwg/ngx-drag-scroll/files/3467545/DragScrollLeak.zip)

**Comment by Anil-sk** [comment]
Any updates on this? when it will be fixed?

**Comment by bfwg** [comment]
hi @Anil-sk , I've been busy with the Angular 9 support lately. I can take a look next week when I have time. Meanwhile, feel free to contribute to the project if you want.

**Comment by Anil-sk** [comment]
hi, @bfwg Thank you. Can you resolve this issue? I really love this and would like to use it on my project :)

**Comment by bfwg** [comment]
@Anil-sk I spent sometime today doing the investigation and it seems this is more an Angular problem than a problem with this library. The Angular issue: https://github.com/angular/angular/issues/13725.

It seems the memory problem will go away if you are building your app with the prod flag. I'm going to close this issue for now and please let me know if you feel that this needs to open again.

Thanks!

**Comment by Anil-sk** [comment]
@bfwg Thank you so much, will let you know if this needs to be open again :)
