### ISSUE TITLE
reachesRightBound && reachesLeftBound output true onInit most of the time. 

### ISSUE THREAD

**Issue by Defmetalhead** [bfwg/ngx-drag-scroll#252]
* **I'm submitting a ...**
  - [* ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
both reachesRightBound && reachesLeftBound are TRUE onInit most of the time. 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**  you can use the demo site as an example or via https://plnkr.co
Print out (reachesLeftBound)="leftBoundStat($event)  &&(reachesRightBound)="rightBoundStat($event)".

Their events read true. 

* **What is the expected behavior?**
Oninit reachesLeftBound should be true, while reachesRightBound should be false. 

I can get around this, but I feel the issue should be fixed.

**Comment by abdelhadibentabet** [comment]
Same issue reachesLeftBound and reachesRightBound output true and moveLeft moveRight nor working while drag scrolling works

**Comment by bfwg** [comment]
Can you provide a https://plnkr.co or codeine?

**Comment by WynieCronje** [comment]
I tried to create an example in stackblitz. While I struggled to reproduce it.  I realized that when using a shared module the Directive for `drag-scroll-item` does not export correctly:

Therefore `@ContentChildren(DragScrollItemDirective) _children: QueryList<DragScrollItemDirective>;` Returns no items.

Resulting in invalid calculations on Left and Right Bounds
https://github.com/bfwg/ngx-drag-scroll/blob/fdd127394b0ecc3a28a6f7e1116a08192ed0e222/projects/ngx-drag-scroll/src/lib/ngx-drag-scroll.component.ts#L405

Example:
https://stackblitz.com/edit/drag-scroll-zero-items

**Comment by WynieCronje** [comment]
Ignore  my previous post :) 

I now know what is happening. If you do not have direct child content. It returns none for:
`@ContentChildren(DragScrollItemDirective) _children: QueryList<DragScrollItemDirective>;`

Example of direct child vs warpping div
https://stackblitz.com/edit/drag-scroll-zero-items-working?file=src/app/app.component.ts

WRAP:
```
<drag-scroll #overviewScroll class="d-block overflow-x-hidden" (dsInitialized)="dsInitialized(overviewScroll)">
	<div class="wrapper">
		<div **drag-scroll-item** *ngFor="let item of items">
			<p>Im a content</p>
		</div>
	</div>
</drag-scroll>
```

DIRECT:
```
<drag-scroll #overviewScroll class="d-block overflow-x-hidden" (dsInitialized)="dsInitialized(overviewScroll)">
	<div **drag-scroll-item** *ngFor="let item of items">
		<p>Im a content</p>
	</div>
</drag-scroll>
```

**Comment by bfwg** [comment]
Thanks for looking into this @WynieCronje . Do you mind creating a PR to resolve the issue since you have a pretty good idea for the it?
