### ISSUE TITLE
 moveLeft, moveRight & moveTo don't work with Angular 9

### ISSUE THREAD

**Issue by keserwan** [bfwg/ngx-drag-scroll#254]
With Angular 9  moveLeft, moveRight & moveTo don't work.
I updated ngx-drag-scroll to the latest 8.0.0-beta.2 because with the latest stable version it was crashing.

**Comment by bfwg** [comment]
Supporting angular 9 is on the way

**Comment by keserwan** [comment]
Thank you for updating on this

**Comment by LukeHowellDev** [comment]
Has there been any progress on this issue? Anything I can do to help?

**Comment by bfwg** [comment]
Hi @LukeHowellDev , can you check again. I just merged #259

**Comment by bfwg** [comment]
Let me know if you are still running into issues and I'll reopen this. Thanks!

**Comment by LukeHowellDev** [comment]
> Hi @LukeHowellDev , can you check again. I just merged #259

@bfwg Looks like that took care of it. Thanks for the quick response.

**Comment by bfwg** [comment]
There seems to be a tiny issue with 9.0.0-beta.1 and I'm working on a fix. Please check later for 9.0.0-beta.2
