### ISSUE TITLE
touch drag does not work

### ISSUE THREAD

**Issue by Fl0r14n** [bfwg/ngx-drag-scroll#256]
* **I'm submitting a ...**
  - [ x] bug report

* **What is the current behavior?**

touch drag does not work

* **What is the expected behavior?**

touch drag should work

* **Please tell us about your environment:**
  
Angular ^9.0.3
ngx-drag-scroll ^8.0.0-beta.2
Browser: Chrome and Samsung Internet

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

in function onMouseDownHandler 

const isTouchEvent = event.type === 'touchstart';

is always false since is listening on mouse down and event type is mousedown even if it's triggered by touch

**Comment by bfwg** [comment]
Angular 9 support is out #259
