### ISSUE TITLE
Can't use other draggable elements in page with drag-scroll

### ISSUE THREAD

**Issue by OctavioSI** [bfwg/ngx-drag-scroll#262]
* **I'm submitting a ...**
  - [ x ] bug report

* **Do you want to request a *feature* or report a *bug*?**
*bug*

* **What is the current behavior?**
I want to use ngx-drag-scroll as an element in my page but in other parts of my screen I need to drag some elements using simple HTML5 draggable feature. If a <drag-scroll> element is present in the page, other HTML5 elements lose their draggable function (actually, draggable function is still there - since dragstart functions are triggered - but I cannot actually drag the elements). 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem you can use the demo site as an example or via https://plnkr.co**
I have assembled a demo here: https://stackblitz.com/edit/angular-ivy-pwbfzd
If I comment out the drag-scroll element, dragging other HTML5 elements with the draggable attribute works fine. If drag-scroll element is present, it does not.

* **What is the expected behavior?**
drag-scroll should not interfere with the dragging feature of other elements outside its scope.

* **What is the motivation / use case for changing the behavior?**
I want to use drag-scroll to drag only a portion of my screen but I still need to drag HTML5 elements with draggable attribute.

* **Please tell us about your environment:**
- Version: 8.0.0-beta.2
- Browser: Chrome Version 83.0.4103.116 (Official Build) (64-bit) | Firefox 78.0.1 (64-bits)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
To fix this, I believe one could restrict the dragging of images prevention only to the inside of drag-scroll scope (lines 255 - 258 of ngx-drag-scroll.component.ts), changing this:
`    // prevent Firefox from dragging images
    this._onDragStartListener = this._renderer.listen('document', 'dragstart', (e) => {
      e.preventDefault();
    });` 
To this:
`    // prevent Firefox from dragging images
    this._onDragStartListener = this._renderer.listen(this._contentRef.nativeElement, 'dragstart', (e) => {
      e.preventDefault();
    });`

I don't know if the 'document' scope is necessary for other reason, but in my use case this ends up influencing with other draggable components.

**Comment by lucaritossa** [comment]
😢  I am in the same situation with an angular project that is using PrimeNG (v8) p-table and its drag system (based on standard HTML5 draggable feature). 
Added ngx-drag-scroll for a specific need (that doesn't involve PrimeNG components) the side effect is a non-working drag&drop feature of PrimeNG components.
