### ISSUE TITLE
Swiping does not work anymore (12.0.0-beta.1)

### ISSUE THREAD

**Issue by Bluejanis** [bfwg/ngx-drag-scroll#282]
* **I'm submitting a ...**
  - [ x] bug report

* **What is the current behavior?**
Swiping to scroll stopped working a couple of days ago. I got the first bug report about that a week ago, but I suspect the issues existed for a few days already.

In the hope of fixing it, I upgraded both this library and Angular from 7 to 12.  But even with Angular 12.1.2 and ngx-drag-scroll 12.0.0-beta.1 swiping does not work anymore.

If I check in the browser, the scroll area has an event listener "wheel", and the individual items have a click listener. There are no pointer event listeners registered at all!

  - Version: 12.0.0-beta.1
  - Browser: [Chrome 92 (via mobile emulation) | Firefox 90 (via mobile emulation) | Firefox Mobile 89 ]

* **Other information** *
I get a warning message in the browser console: 
`Element.setCapture() is deprecated. Use Element.setPointerCapture() instead. For more help https://developer.mozilla.org/docs/Web/API/Element/setPointerCapture`
I cannot say whether ngx-drag-scroll causes that warning, since the console only points to touch-simulator.js:219:19

**Comment by Bluejanis** [comment]
In fact, the last version that would work in my project is ngx-drag-scroll 7.3.6!
An update to 7.3.7 already breaks mobile support. Any idea why?

Was there a breaking change back then?

What seems weird, is that 7.4.3 was working fine until a few weeks ago. Now only older versions like 7.3.4, 7.3.5 & 7.3.6 work.

**Comment by anujsharma-bbd** [comment]
any update on the same ?

**Comment by bfwg** [comment]
13.0.0-beta.1 is out, thanks to @Groschenroman !
