### ISSUE TITLE
Rename the library.

### ISSUE THREAD

**Issue by bfwg** [bfwg/ngx-drag-scroll#40]
## Details

The name `angular2-drag-scroll` is a bit outdated since how angular2+ are simply called angular and angular1.x are called angularjs.

**Comment by joejordanbrown** [comment]
We should have a vote on names, I recommend either `angular-drag-scroll` or `ngx-drag-scroll`.

**Comment by bfwg** [comment]
I like them both. Since this library is essentially a carousel, should we add the word `carousel` or something similar as a part of the name as well? It's hard to keep the name short and intuitive. 😄

**Comment by bfwg** [comment]
Actually, I'm fine with either `angular-drag-scroll` or `ngx-drag-scroll`.

**Comment by akkumar** [comment]
ngx-drag-scroll seems more appropriate. 

But seems like - https://github.com/QuentinPetel/ngx-drag-scroll , a fork of this project already has that name though ( see: https://www.npmjs.com/package/ngx-drag-scroll ) .

**Comment by bfwg** [comment]
That is too bad. I feel `ngx-drag-scroll-all` is a bit too long. It doesn't seem to make much a difference compare`angular-drag-scroll` vs now.

**Comment by yluijten** [comment]
`ngx-draggable-scroll`?

**Comment by akkumar** [comment]
Well - the other thing is to negotiate with the fork owner and try to get the name ngx-drag-scroll though - as that seems the most appropriate.

**Comment by bfwg** [comment]
@yluijten that is a good name, my concern is that this name does not align with the directive name of the library which is `drag-scroll`.

@akkumar I've sent an email to the owner of `ngx-drag-scroll`, hoping that he can feel up the name.

**Comment by QuentinPetel** [comment]
Absolutely for ! I made the fork for that purpose. I will delete it, as well as the npm packages.

**Comment by QuentinPetel** [comment]
Github repo deleted, npm package transfered.

**Comment by bfwg** [comment]
@QuentinPetel Thank you so much. You made my day!

**Comment by bfwg** [comment]
@akkumar I've updated the project name on Github as well as NPM. Can you test the new changes on your machine? I want to make sure everything still works with the new name and everything. 

What is your npm username? I can add your name to this project on NPM if you like.

**Comment by akkumar** [comment]
Works fine. 

Did the following changes. 
```json
"ngx-drag-scroll": "1.5.2"
```
```typescript
import { DragScrollModule } from 'ngx-drag-scroll';
```
So - far so good. 

My npm username is akkumar .
