### ISSUE TITLE
Compilation errors with strict

### ISSUE THREAD

**Issue by DarthPedroFerreira** [bfwg/ngx-drag-scroll#55]
Hi,
I'm getting some compilation errors with strict enable in tsconfig file.

    ERROR in [at-loader] ./node_modules/angular2-drag-scroll/src/angular2-drag-scroll.ts:177:5
        TS2322: Type 'string | null' is not assignable to type 'string'.
      Type 'null' is not assignable to type 'string'.

    ERROR in [at-loader] ./node_modules/angular2-drag-scroll/src/angular2-drag-scroll.ts:278:36
        TS2345: Argument of type 'Node | null' is not assignable to parameter of type 'Node'.
      Type 'null' is not assignable to type 'Node'.

    ERROR in [at-loader] ./node_modules/angular2-drag-scroll/src/angular2-drag-scroll.ts:297:7
        TS2322: Type 'null' is not assignable to type 'HTMLDivElement'.

    ERROR in [at-loader] ./node_modules/angular2-drag-scroll/src/angular2-drag-scroll.ts:351:5
        TS2531: Object is possibly 'null'.

    ERROR in [at-loader] ./node_modules/angular2-drag-scroll/src/angular2-drag-scroll.ts:507:7
        TS2322: Type 'string | null' is not assignable to type 'string'.
      Type 'null' is not assignable to type 'string'.

    ERROR in [at-loader] ./node_modules/angular2-drag-scroll/src/angular2-drag-scroll.ts:508:7
        TS2322: Type 'string | null' is not assignable to type 'string'.
      Type 'null' is not assignable to type 'string'.

skipLibCheck is not working because angular2-drag-scroll has some .ts file in it. I think you should not be distributing the .ts files, just the .js and .d.ts files. Sorry if I'm wrong.

Thank you for you work.
Best regards,
Pedro Ferreira

**Comment by bfwg** [comment]
Hi @DarthPedroFerreira 

Thanks for reporting this. I'm planning to fix this as a part of #41 . With the new build system, we should be able to exclude the ts files and also working with strict mode.

**Comment by yluijten** [comment]
@bfwg 
Has there been any progress concerning this issue?

**Comment by bfwg** [comment]
@yluijten I've just made a PR regarding this issue. Do you want to run a test using #80 and see if that solves the issue?

Thanks for your patient!
