### ISSUE TITLE
Unsupported event target undefined for event mousedown

### ISSUE THREAD

**Issue by deepanshu203** [bfwg/ngx-drag-scroll#61]
Hi,

I am getting error - Unsupported event target undefined for event mousedown when trying to use this module at run time. 
Has anyone else faced the same?

Thanks.

**Comment by bfwg** [comment]
Hey @deepanshu203 ,

It's working fine on my machine, can you give me more details on your browser version and OS please?

**Comment by Fryk** [comment]
Hey after some break on my project I found out I have same problem.
On server everything runs well, but after running webpack in intellij locally thsi error is up.
I didn't run npm install or changed version.
OS: Win10, tested on:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.83 Safari/537.36 Vivaldi/1.91.862.6

**Comment by bfwg** [comment]
Thanks for the report guys, is this issue still present on version 1.5.1? If yes, can you give me the steps to reproduce?

**Comment by bfwg** [comment]
Closing due to no response.
