### ISSUE TITLE
Package.json listed as dependency

### ISSUE THREAD

**Issue by kitsh** [bfwg/ngx-drag-scroll#89]
https://github.com/bfwg/ngx-drag-scroll/blob/develop/package.json#L81

I believe this is causing this error when publishing as a dependency
npm ERR! argv "/usr/local/Cellar/node/5.9.1/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

**Comment by bfwg** [comment]
Thanks for reporting this @kitsh ! I've fixed this in the latest release 1.5.4.
