### ISSUE TITLE
Install commitlint

### ISSUE THREAD

**Issue by akkumar** [bfwg/ngx-drag-scroll#95]
Most of the popular projects ( including Angular/* ) use a commitlint style of project to format the commits better ( distinguish between fix / feat etc. ) that comes in very handy during release logs. 

More details at: 
http://marionebl.github.io/commitlint/#/guides-local-setup . 

would be useful to have it injected in the project for better commit quality.

**Comment by bfwg** [comment]
Great idea, I have put up a PR for this. Do you want to review it?
