### ISSUE TITLE
Stepped scrolling 

### ISSUE THREAD

**Issue by wojofe** [bfwg/ngx-drag-scroll#99]
Hey there!

I have noticed that invoking moveLeft() and moveRight() snaps the carousel to weird locations, sometimes even going backward, when the contents of carousel differ in width.

Kind regards!

**Comment by bfwg** [comment]
Hi @wojofe , thanks for report this. Can you give us an usage example or a code snippet?

**Comment by wojofe** [comment]
Sure, I pushed a minimal tracer angular project here: https://github.com/wojofe/ngx-drag-scroll-stepping-demo/

Does this explain the problem to you?

**Comment by bfwg** [comment]
Nice, I have made a fix in #102 . Version 1.6.3 should resolve the issue. Happy holidays.

**Comment by wojofe** [comment]
Thanks for the fix and same to you.
